export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const PROD_REGISTER_REQUEST = 'PROD_REGISTER_REQUEST';
export const PROD_REGISTER_SUCCESS = 'PROD_REGISTER_SUCCESS';
export const PROD_REGISTER_FAIL = 'PROD_REGISTER_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const PROD_DETAILS_REQUEST = 'PROD_DETAILS_REQUEST';
export const PROD_DETAILS_SUCCESS = 'PROD_DETAILS_SUCCESS';
export const PROD_DETAILS_FAIL = 'PROD_DETAILS_FAIL';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const PROD_UPDATE_PROFILE_REQUEST = 'PROD_UPDATE_PROFILE_REQUEST';
export const PROD_UPDATE_PROFILE_SUCCESS = 'PROD_UPDATE_PROFILE_SUCCESS';
export const PROD_UPDATE_PROFILE_FAIL = 'PROD_UPDATE_PROFILE_FAIL';
export const PROD_UPDATE_PROFILE_RESET = 'PROD_UPDATE_PROFILE_RESET';
